expenses = [
    {
        "id": 1,
        "amount": 100.0,
        "type": "expense",
        "category": "Food",
        "payment_method": "Credit Card",
        "date": "2022-01-01",
        "description": "Dinner at restaurant ABC",
    },
    {
        "id": 2,
        "amount": 50.0,
        "type": "expense",
        "category": "Entertainment",
        "payment_method": "Cash",
        "date": "2022-01-02",
        "description": "Movie tickets",
    },
    {
        "id": 3,
        "amount": 200.0,
        "type": "income",
        "category": "Salary",
        "payment_method": "Direct Deposit",
        "date": "2022-01-03",
        "description": "Monthly salary",
    },
    {
        "id": 4,
        "amount": 30.0,
        "type": "expense",
        "category": "Transportation",
        "payment_method": "Debit Card",
        "date": "2022-01-04",
        "description": "Gas for car",
    },
    {
        "id": 5,
        "amount": 75.0,
        "type": "expense",
        "category": "Groceries",
        "payment_method": "Credit Card",
        "date": "2022-01-05",
        "description": "Weekly groceries",
    },
]
